### ISSUE TITLE
ext-rag does not compile in an ACA 7.3.0 host: ngx-markdown 19 removed MarkedRenderer

### ISSUE THREAD

**Issue by aborroy** [aborroy/alfresco-content-lake-ui#22]
**Type: bug. Effort: S.**

## Summary

The extension does not compile inside the host workspace it is documented to be built in. `README.md` says
to copy `ext-rag` into an Alfresco Content App checkout and build from there; ACA 7.3.0 declares
`ngx-markdown@19.1.1`, and against that version `rag-chat-marked-options.ts` does not resolve.

Because Karma compiles the whole library as one unit, this fails **every** spec in the extension, not just
the chat ones. So there is currently no way to verify any component of this bundle in its host.

## Reproduction

From an ACA 7.3.0 checkout with `ext-rag` copied into `projects/ext-rag`:

```
npx nx test ext-rag --watch=false --browsers=ChromeHeadless
```

```
./projects/ext-rag/src/lib/components/rag-chat/rag-chat-marked-options.ts:9:21-35
  Error: export 'MarkedRenderer' (imported as 'MarkedRenderer') was not found in 'ngx-markdown'
  (possible exports: ..., ExtendedRenderer, ...)

projects/ext-rag/src/lib/components/rag-chat/rag-chat-marked-options.ts:2:24
  error TS2307: Cannot find module 'marked/lib/marked' or its corresponding type declarations.

ERROR [karma-server]: Error: Found 1 load error
```

## Cause

Two independent breakages in the same file, both from the same version jump:

`rag-chat-marked-options.ts:1-2`

```ts
import { MarkedOptions, MarkedRenderer } from 'ngx-markdown';
import { Tokens } from 'marked/lib/marked';
```

1. **`MarkedRenderer` no longer exists.** ngx-markdown 19 removed it; the replacement is
   `ExtendedRenderer`. The error message enumerates the actual export list and it is not in it.
2. **`marked/lib/marked` is not a valid subpath.** ngx-markdown 19.1.1 declares `marked: ^15.0.0` as a
   required peer (`peerDependenciesMeta` is empty, so it is not optional), and marked 15 ships an exports
   map that does not expose `lib/marked`. That path is from the marked 4.x era.

Worth noting for whoever picks this up: the standalone demo UI pins `ngx-markdown@^18.1.0`, where
`MarkedRenderer` still exists. That is why the same markdown code builds there and not here, and why this
went unnoticed.

## Fix

Migrate the file to the ngx-markdown 19 / marked 15 API: `ExtendedRenderer` in place of `MarkedRenderer`,
and import `Tokens` from the package root rather than the internal `lib` path. Then confirm the rendered
behaviour still holds, because the point of this file is that a link in a generated answer opens in a new
tab with `rel="noopener noreferrer"` rather than replacing the application, matching what ACA's own AI
results view does.

Do not pin the extension back to ngx-markdown 18. The host's version is not ours to choose, and the
extension has to build against whatever ACA declares.

## Acceptance criteria

- [ ] `npx nx test ext-rag` compiles and runs inside an ACA 7.3.0 host workspace.
- [ ] Every existing spec in the bundle passes.
- [ ] A link in a generated answer still opens in a new tab with `rel="noopener noreferrer"`.
- [ ] The markdown rendering of an answer is unchanged, checked against a rendered answer rather than by
      reading the diff.

## Blocks

The host-render verification criterion of #21. That change is a status-tile label and is correct in
isolation, but its "verified rendered in the host application" box cannot be ticked while the library does
not compile there.

**Comment by aborroy** [comment]
Fixed in b12519b. `npx nx test ext-rag` now compiles and runs inside an ACA 7.3.0 host: **122 tests passing**,
the first time any spec in this bundle could run there.

**The cause in this issue was half right, and following it alone would not have fixed the build.** Reproducing
gave three errors rather than the two recorded here, and the decisive check was running ACA's *own*
`aca-content` tests: they fail identically, on ACA's own `search-ai-marked-options.ts`, which uses byte-for-byte
the same two imports this file did. So this was never an extension defect.

**ACA 7.3.0's lockfile omits the `marked` peer.** `ngx-markdown@19.1.1` declares `marked: ^15.0.0` as required
-- its `peerDependenciesMeta` is empty -- and `package-lock.json` carries marked only nested under `mermaid`. So
ngx-markdown's own bundle cannot resolve it:

```
./node_modules/ngx-markdown/fesm2022/ngx-markdown.mjs - Error: Module not found:
  Error: Can't resolve 'marked' in '.../node_modules/ngx-markdown/fesm2022'
```

That breaks every markdown consumer in the workspace, ACA's AI results view included, and because Karma
compiles a library as one unit it presents as the whole bundle failing to load. It is a host packaging gap
rather than something this repository can fix, so `npm install marked@^15` is now a documented prerequisite in
the README, with `npm ls marked` as the check to run before suspecting the extension.

**`MarkedRenderer` really is gone, and that is independent of the missing peer.** Worth stating because it looks
like a consequence: I assumed the unresolved `marked` was what made the re-export vanish from the export list,
installed marked first to test it, and it stayed broken.

**The right replacement is marked's `Renderer`, not `ExtendedRenderer`.** This issue suggested the latter, as
does the compiler's own error message, and it is wrong. `MarkedRenderer` was literally
`export { Renderer as MarkedRenderer } from 'marked'`, so importing `Renderer` is the migration that changes no
behaviour. `ExtendedRenderer` is ngx-markdown's own subclass carrying two `ɵNgxMarkdownRenderer...` marker
properties that record whether it has already extended a renderer; constructing one leaves those undefined, and
it makes the object unusable with marked's `use({ renderer })`, which validates every key against the known
renderer methods. A new spec caught it immediately:

```
Error: renderer 'ɵNgxMarkdownRendererExtendedForExtensions' does not exist
```

**`marked/lib/marked` resolves once marked is installed**, despite not appearing in marked 15's exports map,
because TypeScript falls back to filename lookup. A private path that happens to work, so `Tokens` now comes
from the package root.

## Against the criteria

- [x] `npx nx test ext-rag` compiles and runs inside an ACA 7.3.0 host workspace.
- [x] Every existing spec in the bundle passes -- 122, and none of them could run before.
- [x] A link still opens in a new tab with `rel="noopener noreferrer"`.
- [x] The markdown rendering is checked against a rendered answer rather than by reading the diff.

On that last point: this file had **no test at all**, which is why it went on importing something that had been
removed. It has three now, and they assert against rendered markdown rather than by calling the hook directly --
the hook's signature is the thing that changes between marked majors, so a test that invoked it by hand would
keep passing against a renderer marked no longer drives that way.

This also unblocks #21, whose last two criteria needed the bundle to compile here.

Closing.
